version: '3'
services:
  nblog2:
    image: 'nblog2:latest'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    command:
      - go run main.go
    ports:
      - '3000:3000'
    volumes:
      - './vendor:/usr/local/go/src/nblog2/'
    networks:
      back:
        ipv4_address: 172.16.238.10
    stdin_open: true
    tty: true
    depends-on:
      - mysql
  mysql:
    image: 'mysql:8.0.12'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './mysql/config/:/etc/mysql/conf.d/'
      - './mysql/data/:/var/lib/mysql/'
    networks: 
      back:
        ipv4_address: 172.16.238.5
    restart:
      always
networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
