version: '3.3'

services:
  nblog2:
    image: "nblog:latest"
    build:
      context: .
        
    command: go run main.go
    ports:
      - 3000:3000

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      PORT: 3000
      
    stdin_open: true

    tty: true

    links:
      - mysql
  mysql:
    image: mysql:8.0.12
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  notused: